### Cadastrar uma nova tarefa
POST https://localhost:5001/api/tarefa/create
Content-Type: application/json

{
    "Nome" : "Prova",
    "Prazo" : "29092021",
    "Descrição": "string",
    "Data Conclusão": "2021-09-29T12:04:31.836Z"
}

### Listar todos os tarefas
GET https://localhost:5001/api/tarefa/list

{
    "Id" : "1",
    "Nome" : "Prova",
    "Prazo" : "01012021",
    "Descrição": "string",
    "Data Conclusão": "2021-09-29T12:04:31.836Z"
}
